name: Get Installed Software List on Windows
  hosts: windows_hosts
  tasks:
    - name: Get Installed Software List
      win_shell: Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName
      register: installed_software
