---
- name: Gather software, CPU, and memory info from Windows server
  hosts: windows_servers
  tasks:
    - name: Get installed software
      win_command: Get-WmiObject -Class Win32_Product | Select-Object Name, Version
      register: installed_software

    - name: Get CPU and memory info
      win_command: Get-WmiObject -Class Win32_Processor | Select-Object Name, NumberOfCores, NumberOfLogicalProcessors, MaxClockSpeed, Manufacturer; Get-WmiObject -Class Win32_OperatingSystem | Select-Object TotalVisibleMemorySize
      register: system_info

    - name: Display results in JSON format
      debug:
        var:
          software: "{{ installed_software.stdout | from_json }}"
          system_info: "{{ system_info.stdout | from_json }}"
      vars:
        ansible_stdout_encoding: 'utf-8'
