- name: Get list of installed software
  hosts: 172.16.0.67
  tasks:
    - name: Get installed software
      ansible.windows.win_command: "Get-WmiObject -Class Win32_Product | Select-Object -Property Name, Version"
      register: installed_software

    - name: Output installed software
      ansible.builtin.debug:
        var: installed_software.stdout_lines
