name: Get Installed Software List on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Get Installed Software List
      win_shell: Get-WmiObject -Class Win32_Product | Select-Object Name
      register: installed_software
