- name: List installed software not running on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Get installed software
      ansible.windows.win_shell: |
        Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | 
        Select-Object DisplayName, DisplayVersion
      register: installed_software

    - name: Filter installed software not running
      set_fact:
        software_not_running: "{{ installed_software.stdout | from_json | selectattr('Name', 'notin', running_processes.stdout) | list }}"

    - debug:
        var: software_not_running
