- name: Get list of installed software and system information
  hosts: 172.16.0.67
  tasks:
    - name: Get installed software
      ansible.windows.win_shell: |
        Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | 
        Select-Object DisplayName, DisplayVersion
      register: installed_software

    - name: Get MAC Address
      ansible.windows.win_shell: Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object { $_.MACAddress -ne $null } | Select-Object -First 1 MACAddress
      register: mac_address

    - name: Get IP Address
      ansible.windows.win_shell: Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object { $_.IPAddress -ne $null } | Select-Object -ExpandProperty IPAddress
      register: ip_address

    - name: Output installed software and system information
      ansible.builtin.debug:
        msg: |
          Installed Software:
          {{ installed_software.stdout_lines }}
          IP Address: {{ ip_address.stdout }}
          MAC Address: {{ mac_address.stdout }}
