---
- name: Gather Windows system information
  hosts: 172.16.0.67
  tasks:
    - name: Gather installed software
      win_package_facts:
        gather_subset: all
      register: installed_software

    - name: Gather running processes
      win_command: tasklist /FO CSV
      register: running_processes

    - name: Output installed software in YAML format
      debug:
        msg: "{{ installed_software.packages | to_nice_yaml }}"

    - name: Output running processes in YAML format
      debug:
        msg: "{{ running_processes.stdout_lines | to_nice_yaml }}"
