- name: List installed software not running on Windows
  hosts: windows
  tasks:
    - name: Get installed software
      ansible.windows.win_shell: |
        Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*" | 
        Select-Object DisplayName, DisplayVersion
      register: installed_software

    - name: Filter installed software not running
      set_fact:
        software_not_running: "{{ installed_software.stdout | json_query(query) }}"
      vars:
        query: "[? !contains(@, '{{ running_processes.stdout }}[*]')].{Name: Name, Version: Version}"

    - debug:
        var: software_not_running
