- name: Get System Information and Installed Software List on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Get MAC Address
      win_shell: Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object { $_.MACAddress -ne $null } | Select-Object -First 1 MACAddress
      register: mac_address

    - name: Get IP Address
      win_shell: Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object { $_.IPAddress -ne $null } | Select-Object -ExpandProperty IPAddress
      register: ip_address

    - name: Get Installed Software List
      win_shell: Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName
      register: installed_software

    - debug:
        msg: 
          - "MAC Address: {{ mac_address.stdout_lines[0] }}"
          - "IP Address: {{ ip_address.stdout_lines[0] }}"
          - "Installed Software List:"
          - "{{ installed_software.stdout_lines }}"
